[build]
  base = "/"
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  VITE_API_URL = "https://catch-pairs-bodies-confidence.trycloudflare.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"