name = "znapfile-gateway"
main = "cloudflare-gateway.js"
compatibility_date = "2023-05-18"

[env.production]
workers_dev = true
route = "znapfile.com/api/*"

[env.production.vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"