name = "znapfile-quantum-router"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "api.znapfile.com/*", custom_domain = true }
]

[env.production.vars]
ENVIRONMENT = "production"